/**
 * Request payload for user login authentication.
 */
export interface LoginRequest {
  /** User's email address */
  email: string;
  /** User's password */
  password: string;
}

/**
 * Response from a login attempt.
 */
export interface LoginResult {
  /** Whether the login was successful */
  success: boolean;
  /** Error message if login failed */
  error: string;
}

/**
 * Response containing authentication token after successful login.
 */
export interface TokenResponse {
  /** Whether the token was successfully generated */
  success: boolean;
  /** JWT authentication token */
  token: string;
  /** Type of token (e.g., "Bearer") */
  tokenType: string;
}

/**
 * Request payload for new user registration.
 */
export interface RegisterRequest {
  /** User's email address */
  email: string;
  /** User's chosen password */
  password: string;
  /** Password confirmation (must match password) */
  password_confirm: string;
}

/**
 * Response from a registration attempt.
 */
export interface RegisterResult {
  /** Whether the registration was successful */
  success: boolean;
}

/**
 * Request payload for sending a chat message.
 */
export interface ChatRequest {
  /** The user's message content */
  message: string;
  /** The language model to use for generating a response */
  llm: string;
}

/**
 * Metadata for a chat thread.
 */
export interface ThreadMetaData {
  /** Display title for the thread */
  title: string;
  /** Unique identifier for this thread */
  thread_id: string;
  /** The most recent LLM used in this thread */
  last_llm_used: string;
  /** ISO 8601 timestamp of when the thread was created */
  created_at: string;
  /** ISO 8601 timestamp of when the thread was last updated */
  updated_at: string;
}

/**
 * Response containing a list of thread metadata.
 */
export interface HistoryResult {
  /** Whether the request was successful */
  success: boolean;
  /** Array of thread metadata */
  threads: ThreadMetaData[];
}

/**
 * Response containing the full message history for a thread.
 */
export interface ThreadHistoryResult {
  /** Whether the request was successful */
  success: boolean;
  /** Array of messages in the thread */
  messages: Message[];
}

/**
 * Response from a thread deletion request.
 */
export interface DeleteThreadResult {
  /** Whether the deletion was successful */
  success: boolean;
  /** The ID of the deleted thread */
  thread_id: string;
}

/**
 * Response from a project deletion request.
 */
export interface DeleteProjectResult {
  /** Whether the deletion was successful */
  success: boolean;
}

/**
 * A single message in a chat conversation.
 */
export interface Message {
  /** The position of this message in the conversation (0-indexed) */
  index: number;
  /** The text content of the message */
  content: string;
  /** The language model used (for AI messages) or empty string (for user messages) */
  llm: string;
  /** Whether this message was sent by the user or generated by AI */
  message_type: "user" | "ai";
  /** Unique identifier for this message */
  message_id?: string;
  /** The thread this message belongs to */
  thread_id?: string;
  /** ISO 8601 timestamp of when the message was created */
  created_at?: string;
}

/**
 * Metadata for a project.
 */
export interface ProjectsMetaData {
  /** Unique identifier for this project */
  project_id: string;
  /** Display title for the project */
  title: string;
  /** ISO 8601 timestamp of when the project was created */
  created_at: string;
  /** ISO 8601 timestamp of when the project was last updated */
  updated_at: string;
}

/**
 * Response containing a list of project metadata.
 */
export interface ProjectsResult {
  /** Whether the request was successful */
  success: boolean;
  /** Array of project metadata */
  projects: ProjectsMetaData[];
}

/**
 * Metadata for an available language model.
 */
export interface ModelMetaData {
  /** The provider identifier (e.g., "openai", "anthropic") */
  provider: string;
  /** Human-readable provider name (e.g., "OpenAI", "Anthropic") */
  provider_display_name: string;
  /** The model identifier (e.g., "gpt-4", "claude-3-opus") */
  model: string;
  /** Human-readable model name */
  display_name: string;
}

/**
 * Response containing a list of supported language models.
 */
export interface SupportedModelsResult {
  /** Whether the request was successful */
  success: boolean;
  /** Array of available model metadata */
  supported_models: ModelMetaData[];
}

/**
 * Full project details including threads.
 */
export interface ProjectResult {
  /** Whether the request was successful */
  success: boolean;
  /** Unique identifier for this project */
  project_id: string;
  /** Display title for the project */
  title: string;
  /** Custom instructions/system prompt for the project */
  instructions: string;
  /** ISO 8601 timestamp of when the project was created */
  created_at: string;
  /** ISO 8601 timestamp of when the project was last updated */
  updated_at: string;
  /** Array of threads belonging to this project */
  threads?: ThreadMetaData[];
}

/**
 * Response from a project update request.
 */
export interface ProjectUpdateResult {
  /** Whether the update was successful */
  success: boolean;
  /** The ID of the updated project */
  project_id: string;
}

/**
 * Request payload for updating a project.
 */
export interface ProjectUpdateRequest {
  /** The ID of the project to update */
  project_id: string;
  /** Updated custom instructions/system prompt */
  instructions: string;
  /** Updated project title */
  title: string;
}

/**
 * Response from creating a new project.
 */
export interface NewProjectResult {
  /** Whether the creation was successful */
  success: boolean;
  /** The ID of the newly created project */
  project_id: string;
}

/**
 * Request payload for creating a new project.
 */
export interface NewProjectRequest {
  /** Title for the new project */
  title: string;
}

/**
 * Standardized API error response.
 */
export interface ApiError {
  /** Human-readable error message */
  message: string;
  /** HTTP status code */
  statusCode: number;
}
